# Spring properties
spring:
  application:
     name: cursos-service
  datasource:
    url: jdbc:postgresql://localhost:5432/microservico
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 5001   # HTTP (Tomcat) port